import { useEffect, useState } from 'react';
import type { CSSProperties } from 'react';
import { createPortal } from 'react-dom';
import { Link } from 'react-router-dom';
import { Code, ExternalLink, FolderOpen, X } from 'lucide-react';
import './Projects.css';

type FolderColour = 'orange' | 'sage' | 'forest' | 'blue' | 'lilac' | 'cream';
interface Project { id:string; title:string; shortLabel:string; description:string; technologies:string[]; detailsUrl?:string; githubUrl?:string; liveUrl?:string; folderColour:FolderColour; fileCount:string; category:string; }
const PROJECTS: Project[] = [
{ id:'project-one', title:'Administrative Website for a Family Business - Academic Project', shortLabel:'FAMILY_BUSINESS_01', description:'Built a business management web app using C#, ASP.NET MVC, SQL Server, Entity Framework, and JavaScript, with a focus on structured data management and maintainable architecture.', technologies:['C#','ASP.NET MVC','.NET','SQL Server'], detailsUrl:'', githubUrl:'https://github.com/dacevedocubillo/WebAdminSystem', folderColour:'orange', fileCount:'04 FILES', category:'FULL-STACK BUILD' },
{ id:'project-two', title:'Vacation Management System — Academic Project', shortLabel:'UNIVERSITY_02', description:'Developed a vacation management system for a university using C#, ASP.NET MVC, and SQL Server, including employee leave requests, approvals and reporting.', technologies:['C#','.NET','ASP.NET MVC','SQL Server'], detailsUrl:'', githubUrl:'https://github.com/dacevedocubillo/VAP-Manager', folderColour:'sage', fileCount:'06 FILES', category:'ACADEMIC SYSTEM' },
{ id:'project-three', title:'Alura Geek — Music Store', shortLabel:'MUSIC_STORE_03', description:'Responsive front-end music store featuring album collections, category navigation, live search, interactive product previews, a matching account experience and mobile-friendly layouts.', technologies:['HTML','CSS','JavaScript','Responsive Design'], detailsUrl:'', liveUrl:'https://dacevedocubillo.github.io/Alura-Geek/', githubUrl:'https://github.com/dacevedocubillo/Alura-Geek', folderColour:'forest', fileCount:'05 FILES', category:'FRONT-END E-COMMERCE' },
{ id:'project-four', title:'University Academic Management System', shortLabel:'PORTFOLIO_04', description:'A web-based academic management system for managing students, courses, enrollment, grades, campuses, academic terms, user roles and reports.', technologies:['C#','.NET','ASP.NET MVC','SQL Server'], detailsUrl:'', githubUrl:'https://github.com/dacevedocubillo/SistemaUniversitario', folderColour:'blue', fileCount:'03 FILES', category:'ACADEMIC SYSTEM' },
];
const Projects=()=>{const[openProjectId,setOpenProjectId]=useState<string|null>(null);const openProject=PROJECTS.find(p=>p.id===openProjectId)??null;useEffect(()=>{if(!openProject)return;const html=document.documentElement,body=document.body,ho=html.style.overflow,bo=body.style.overflow,bp=body.style.paddingRight,w=window.innerWidth-html.clientWidth;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpenProjectId(null)};html.style.overflow='hidden';body.style.overflow='hidden';if(w>0)body.style.paddingRight=`${w}px`;window.addEventListener('keydown',esc);return()=>{html.style.overflow=ho;body.style.overflow=bo;body.style.paddingRight=bp;window.removeEventListener('keydown',esc)}},[openProject]);
const projectModal=openProject&&typeof document!=='undefined'?createPortal(<div className="pixel-project-modal" role="dialog" aria-modal="true" aria-labelledby="pixel-project-dialog-title" onClick={e=>{if(e.target===e.currentTarget)setOpenProjectId(null)}}><article className={`pixel-project-window pixel-window-${openProject.folderColour}`} onClick={e=>e.stopPropagation()}><header className="pixel-project-window-header"><div><FolderOpen size={16} aria-hidden="true"/><span>{openProject.shortLabel}/{openProject.id}.folder</span></div><button type="button" onClick={()=>setOpenProjectId(null)} aria-label="Close project folder" autoFocus><X size={17} aria-hidden="true"/></button></header><div className="pixel-project-window-body"><div className="pixel-project-preview"><div className="pixel-project-preview-grid" aria-hidden="true"/><span className="pixel-project-preview-folder" aria-hidden="true"><i/><b/></span><span className="pixel-project-preview-label">{openProject.category}</span><strong>{openProject.title}</strong><small>Daniela's software development project archive</small></div><div className="pixel-project-information"><span className="pixel-project-information-label">PROJECT_INFO.TXT</span><h3 id="pixel-project-dialog-title">{openProject.title}</h3><p>{openProject.description}</p><div className="pixel-project-tech"><span>TOOLS + STACK</span><div>{openProject.technologies.map(t=><i key={t}>{t}</i>)}</div></div><div className="pixel-project-actions">{openProject.liveUrl&&<a href={openProject.liveUrl} target="_blank" rel="noopener noreferrer"><ExternalLink size={15} aria-hidden="true"/>Live Demo</a>}{openProject.detailsUrl&&<Link to={openProject.detailsUrl} onClick={()=>setOpenProjectId(null)}><ExternalLink size={15} aria-hidden="true"/>Open case study</Link>}{openProject.githubUrl&&<a href={openProject.githubUrl} target="_blank" rel="noopener noreferrer"><Code size={15} aria-hidden="true"/>View code</a>}</div></div></div><footer className="pixel-project-window-footer"><span>{openProject.fileCount}</span><span>DANIELA'S PROJECT ARCHIVE</span></footer></article></div>,document.body):null;
return <><section id="projects" className="pixel-projects-section"><div className="pixel-projects-background" aria-hidden="true"><span className="pixel-project-leaf pixel-project-leaf-one"/><span className="pixel-project-leaf pixel-project-leaf-two"/><span className="pixel-project-flower pixel-project-flower-one"/><span className="pixel-project-flower pixel-project-flower-two"/></div><div className="pixel-projects-shell"><header className="pixel-projects-header"><div><span className="pixel-projects-kicker">PROJECT_ARCHIVE.EXE</span><h2>Projects</h2><p>Open a folder to explore the story, tools and code behind each build.</p></div><div className="pixel-projects-status" aria-hidden="true"><span>ARCHIVE STATUS</span><strong>{PROJECTS.length} FOLDERS FOUND</strong></div></header><div className="pixel-folder-grid">{PROJECTS.map((project,index)=><button key={project.id} type="button" className={`pixel-project-folder pixel-folder-${project.folderColour}`} onClick={()=>setOpenProjectId(project.id)} aria-label={`Open ${project.title} project folder`} style={{'--folder-delay':`${index*80}ms`} as CSSProperties}><span className="pixel-folder-stack" aria-hidden="true"><span className="pixel-folder-paper pixel-folder-paper-back"><i/><i/><i/></span><span className="pixel-folder-back"><span className="pixel-folder-tab">{project.shortLabel}</span></span><span className="pixel-folder-paper pixel-folder-paper-front"><span>{project.category}</span><strong>{project.title}</strong><div>{project.technologies.slice(0,3).map(t=><i key={t}>{t}</i>)}</div></span><span className="pixel-folder-front"><span className="pixel-folder-flower"><i/><i/><i/><i/><b/></span><span className="pixel-folder-sticker">OPEN</span></span></span><span className="pixel-folder-caption"><span><strong>{project.title}</strong><small>{project.category}</small></span><span><FolderOpen size={16} aria-hidden="true"/>{project.fileCount}</span></span></button>)}</div><div className="pixel-projects-footer"><span>SELECT FOLDER</span><span>CLICK TO OPEN // ESC TO CLOSE</span></div></div></section>{projectModal}</>};export default Projects;